### ISSUE TITLE
Fails due to inconsistent read lengths

### ISSUE THREAD

**Issue by dude-meister** [Zymo-Research/figaro#14]
Great idea as I always have troubles to find a standardized method for defining the trimming parameters in DADA2. However, when I try running figaro.py with my data (16S V3/V4, Illumina MiSeq demultiplexed): 

```
python figaro.py -i ./fastq -o ./output -f 17 -r 21 -a 460
```
I always get the following error:

```
Forward reads appear to not be of consistent length. {(301, 0.01)}
Reverse reads appear to not be of consistent length. {(300, 0.03878787878787879)}
```

I also tried it with older fastq files (> 1 year) and I always get the same error. How can I handle the problem? Is there a way to bypass the issue?

EDIT: The files I used are the ones Illumina directly uploads to BaseSpace (e.g. XXX_S49_L001_R1_001.fastq.gz, XXX_S49_L001_R2_001.fastq.gz) and have not been changed or trimmed.

Thanks for your help!

**Comment by michael-weinstein** [comment]
I have seen some machines/pipelines where the trimming happens automatically, possibly for adapter removal.
I have it set up right now to not allow for quality modeling against trimmed reads because I have not tested my error accumulation modeling against reads that have already been trimmed.  I could not be sure it will remain valid.
Please try checking your miSeq for any settings that might automatically trim.  If you are unable to get it fixed by tomorrow, please reply again.  One of my colleagues here at Zymo knows about a specific issue that was causing unintentional trimming; I can ask her about it when she's in.

**Comment by michael-weinstein** [comment]
I'm going to tag @AishaniPrem here, since she's more familiar with the unintended trimming issues than I am.

**Comment by dude-meister** [comment]
Thanks for your quick response. I got in touch with the lab technician and they will check the Illumina settings. I'll give you an update as soon as I hear from them.

However, I managed to circumvent the issue by removing sequences that do not have the target length 301/300 using cutadapt with 96% of the sequences remaining. Afterwards figaro worked great. 👍 

Not sure if this is a common issue, would be great though to include sequences with variable lengths.

**Comment by michael-weinstein** [comment]
I wish I could, but I worry about the validity of the error accumulation models when the reads have been already trimmed to different lengths.  There's a risk that someone trimmed for quality, which could make my model behave in unexpected ways.

**Comment by HanneloreH** [comment]
I'm suffering from the same problem as described above (2x250bp read length) and similarly used cutadapt to remove reads <250bp. However Figaro keeps giving the error even though there's no clear difference in read length anymore:

""" _ERROR after removing <250bp reads:_
Forward read files appear to be of different lengths or of varied lengths. {(251, 0.01), (251, 0.06575757575757575), (251, 0), (251, 0.05696969696969697), (251, 0.08272727272727273), (251, 0.15545454545454546), (251, 0.07434343434343434), (251, 0.04797979797979798), (251, 0.029393939393939396), (251, 0.12878787878787878), (251, 0.09090909090909091), (251, 0.09888888888888889), (251, 0.03878787878787879), (251, 0.019797979797979797)}
Reverse read files appear to be of different lengths or of varied lengths. {(251, 0.08272727272727273), (251, 0.07434343434343434), (251, 0.05696969696969697), (251, 0.01), (251, 0.12161616161616161), (251, 0.14252525252525253), (251, 0.029393939393939396), (251, 0.16161616161616163), (251, 0.09090909090909091), (251, 0.13575757575757577), (251, 0.16757575757575757), (251, 0.10666666666666666), (251, 0.12878787878787878), (251, 0.11424242424242424), (251, 0.03878787878787879), (251, 0.019797979797979797), (251, 0.06575757575757575), (251, 0.04797979797979798), (251, 0.09888888888888889)}
Forward reads appear to not be of consistent length. {(251, 0.01), (251, 0.06575757575757575), (251, 0), (251, 0.05696969696969697), (251, 0.08272727272727273), (251, 0.15545454545454546), (251, 0.07434343434343434), (251, 0.04797979797979798), (251, 0.029393939393939396), (251, 0.12878787878787878), (251, 0.09090909090909091), (251, 0.09888888888888889), (251, 0.03878787878787879), (251, 0.019797979797979797)}
Reverse reads appear to not be of consistent length. {(251, 0.08272727272727273), (251, 0.07434343434343434), (251, 0.05696969696969697), (251, 0.01), (251, 0.12161616161616161), (251, 0.14252525252525253), (251, 0.029393939393939396), (251, 0.16161616161616163), (251, 0.09090909090909091), (251, 0.13575757575757577), (251, 0.16757575757575757), (251, 0.10666666666666666), (251, 0.12878787878787878), (251, 0.11424242424242424), (251, 0.03878787878787879), (251, 0.019797979797979797), (251, 0.06575757575757575), (251, 0.04797979797979798), (251, 0.09888888888888889)}
"""

What may be the problem?

**Comment by michael-weinstein** [comment]
Apologies for the delay on this again.  I have been working on the ability to handle variable length reads, but this has temporarily taken a backseat to ZymoTransmit, as that program is currently supporting a significant amount of COVID-19 public health reporting for the state of California.  I expect to get back to this shortly now that I have completed its major update to support the new CDPH gateway.

**Comment by sreejata-b** [comment]
Hi @michael-weinstein, I am running into a similar issue with variable read lengths and was wondering if this issue was fixed with a newer version of figaro? Thanks in advance. Also, I get this other error with another dataset which does not have variable read lengths : "Zero Division error: division by zero". I have had good luck with figaro before and hence would like to continue to use it pending solving these errors.

**Comment by soluna1** [comment]
Hi, I'm having the same problem running 16s metabarcoding (primers: 515F-Y/926R matching the V4 and V5 hypervariable regions, NovaSeq PE250 Illumina). 

As input I'm using sequences without primers (previously removed with cutadapt), length ranging from 219 to 246 (after primer removal). Figaro parameters are: -a 400 -f 19 -r 20.

The error from Figaro looks like:
`Forward read files appear to be of different lengths or of varied lengths. {(231, 0.05898989898989899), (231, 0.029393939393939396), (231, 0.04), (231, 0.06060606060606061)`

`Reverse read files appear to be of different lengths or of varied lengths. {(230, 0.01), (230, 0), (230, 0.04), (230, 0.020202020202020204),`

and also, 

`Forward reads appear to not be of consistent length. {(231, 0.05898989898989899), (231, 0.029393939393939396), (231, 0.04),`

`Reverse reads appear to not be of consistent length. {(230, 0.01), (230, 0), (230, 0.04), (230, 0.020202020202020204), (230, 0.05898989898989899), (230, 0.03878787878787879),`

Is there a way to handled this error? 
Also, the Figaro report is empty, so I can only get info from the shell.

Thanks in advance, hope this can be solved, the app seems to be very useful for dada2 processing.
