### ISSUE TITLE
FASTQ naming scheme

### ISSUE THREAD

**Issue by zhonglinma** [Zymo-Research/figaro#21]
Hi, I'm using Figaro to get DADA2 trimming parameters, and I got "ValueError: 3-BW-3.R2.fq.gz does not appear to be a valid Illumina file name", I don't know what a valid Illumina file name looks like, I haven't modified my filename after I got it from sequencing company, can you help me with this? by the way, my amplicon primer is 515F/806R, so my amplicon length is 806-515=291? the appendix shows my file name.
Thank you very much!

**Comment by michael-weinstein** [comment]
I should be able to make a naming scheme for this.  Can you send me an email and we can work it out?  I have a pretty good idea of how your scheme works already.

**Comment by michael-weinstein** [comment]
I would suggest using an underscore as the delimiter before the read direction (R2) instead of a dot.  Using dots as the delimiter for that portion can cause confusion when most times an underscore is used.  If you make that change, I already have a naming scheme that will work for it (nononsense).

**Comment by jolespin** [comment]
At our sequencing core we use [id_sample]_R1_001.fastq.gz and [id_sample]_R2_001.fastq.gz

How can I use this? 

Can you add a parameter like --naming_scheme [ID]_R%_001.fastq.gz where it would pick up that ID is the id_sample and there are R1 and R2 of it?
