### ISSUE TITLE
Figaro stops at some point

### ISSUE THREAD

**Issue by termithorbor** [Zymo-Research/figaro#22]
Hi all,

this is the error I am encountering: 

Traceback (most recent call last):
  File "figaro.py", line 213, in <module>
    resultTable, forwardCurve, reverseCurve = figaroSupport.trimParameterPrediction.performAnalysisLite(parameters.inputDirectory.value, parameters.minimumCombinedReadLength.value, subsample =  parameters.subsample.value, percentile = parameters.percentile.value, forwardPrimerLength=parameters.forwardPrimerLength.value, reversePrimerLength=parameters.reversePrimerLength.value, namingStandardAlias=fileNamingStandard)
  File "/home/tsieksmeyer/figaro/figaroSupport/trimParameterPrediction.py", line 436, in performAnalysisLite
    forwardReadLength, reverseReadLength = checkReadLengths(fastqList)
  File "/home/tsieksmeyer/figaro/figaroSupport/trimParameterPrediction.py", line 398, in checkReadLengths
    raise fastqHandler.FastqValidationError("Unable to validate fastq files enough to perform this operation. Please check log for specific error(s).")
figaroSupport.fastqHandler.FastqValidationError: Unable to validate fastq files enough to perform this operation. Please check log for specific error(s).

Does anybody has an idea what the problem is? The log file is empty.

Thanks :)

**Comment by michael-weinstein** [comment]
This is generally produced when it can't read the FASTQ file enough to validate it.  Check to see if you have an empty FASTQ file in there.  If not, I can set up a quick check to see what could be causing the issue.

Michael

**Comment by whats-in-the-box** [comment]
I have the same issue. Before the error @termithorbor posted, I also got:

Forward read files appear to be of different lengths or of varied lengths.
Reverse read files appear to be of different lengths or of varied lengths.
Forward reads appear to not be of consistent length. 
Reverse reads appear to not be of consistent length.

I definitely do not have an empty fastq files here. Any help is appreciated. 

Max

**Comment by michael-weinstein** [comment]
Ah, that one is a bit different.  As the error message says, the issue is that within each file, there are reads of varying lengths.  FIGARO will not currently support the analysis on variable length reads, but I am working on an update that will handle this.  Apologies that it is taking me so long, I am tied up with a different project that appears to have a much tighter schedule and potentially higher stakes.  I will make the update.
