### ISSUE TITLE
non overlapping reads

### ISSUE THREAD

**Issue by nomascus** [Zymo-Research/figaro#23]
Hi, I have really enjoyed using FIGARO so far. Recently, I was given a set of non-overlapping illumina reads to work with--obviously not ideal. I'm trying to see what I can do with these data, but I'm wondering, is there is any way to run FIGARO on reads that don't overlap?

**Comment by michael-weinstein** [comment]
Not so much. It is based around trying to get overlap while maximizing quality. My bigger question is how you plan to analyze them with DADA2.

**Comment by nomascus** [comment]
Ok, thanks for letting me know. There is a filterAndTrim option to run DADA2 that adds 10 N's between the reads so that the algorithm can proceed (justConcatenate = TRUE) for cases like this. My other thought is to run DADA2 with only the forward reads. Either way I'll have to accept some limitations, I suppose.
