### ISSUE TITLE
missing nameless outputs

### ISSUE THREAD

**Issue by handibles** [Zymo-Research/figaro#27]
Sent a [PR](https://github.com/Zymo-Research/figaro/pull/26) , but there are two other non-critical snags that are probably better mentioned here (possible related to the PR):

1. firstly, from 132 ```fastqs```, I get back 118 entries in the ```JSON``` output (```log``` is empty), suggesting some files are silently failing (same run, same naming convention). I would check the missing files, but see 2:
2. no names are appended to the outputs in the ```JSON``` - not sure if this is intended functionality. 

Partially due to 1&2, I'll probably end up taking subjective averages of these objective parameters output - can I ask what is the envisioned next step for e.g. a ```DADA2``` run incorporating this data (esp. in ```JSON```)? Pass values to ```filtAndTrim()``` as a vector of parameters?

As ever Dev, thanks for the time put into this.

**Comment by handibles** [comment]
drat, spotted duplicate issue in list. Will defer there.

**Comment by michael-weinstein** [comment]
I think I fixed some of the more critical issues related to this.  Going to see about making some bigger changes in a version 2 that should allow for some variability in the read-lengths.
