### ISSUE TITLE
Forward read files appear to be of different lengths or of varied lengths.

### ISSUE THREAD

**Issue by weibokong27** [Zymo-Research/figaro#30]
When I try running figaro.py with my data (16S V3/V4, Illumina HiSeq):

`python $PWD/figaro/figaro.py -i trim -o trim -f 1 -r 1 -a 465 -F zymo`

Wrong:

`Forward read files appear to be of different lengths or of varied lengths. {(178, 45.74505050505051), (179, 137.22939393939393), (178, 76.54333333333334), (179, 16.32030303030303), (180, 2.199090909090909), (180, 2.89), (175, 277.8920202020202).............`

Excuse me, how can I solve this problem?

**Comment by michael-weinstein** [comment]
It looks like your reads are of variable length in each direction.  While I am currently working on a new version of the program that can handle variable lengths in reads to some extent, I am seeing some big differences in read lengths here.  Have these reads been trimmed before FIGARO?  If so, that is not a good practice.
