### ISSUE TITLE
ImportError trying to run figaro

### ISSUE THREAD

**Issue by elpape** [Zymo-Research/figaro#31]
Hi,

I'm trying to run figaro to determine trimming parameters for the dada2 pipeline, but cannot seem to get it to work.

I get the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/ellen/figaro/figaro/figaro.py", line 3, in <module>
    from . import environmentParameterParser, fileNamingStandards, fastqAnalysis, trimParameterPrediction
ImportError: attempted relative import with no known parent package
```

I installed the command line version of figaro. After, I tried to run figaro using

`python3 figaro.py -i /mnt/e/18S/cutadapt/cutadapt_non_int_adapt/ -o /mnt/e/18S/figaro/ -a 400 -f 1 -r 1`

Any idea on what the problem might be?

Thanks!
Ellen

**Comment by michael-weinstein** [comment]
Yes, the importing got messed up when this was set up to also install as a python package.  I believe I have deployed a fix for that tonight.
