### ISSUE TITLE
read-specific maxExpectedError and trim length

### ISSUE THREAD

**Issue by akhst7** [Zymo-Research/figaro#33]
Hi.  I have a basic newbie question.   Figaro punches out  read-specific `maxExpectedError` and trim length but to DADA2 `filterAndTrim` takes only single value for each parameters.  So how do l feed each individual read-specific maxExpectedErrors and trim length  to DADA2` filterAndTrim `?  Find a range or average ? 

Thanks.

**Comment by michael-weinstein** [comment]
The top result (highest scoring, listed at the top of the output) is the one you want to use to fill in the filterAndTrim parameters.

I'm going to go ahead and steal this from my UCLA course slides:

![image](https://user-images.githubusercontent.com/9012909/116578343-2b659280-a8c6-11eb-97e5-d159482f8eff.png)

**Comment by akhst7** [comment]
@michael-weinstein 

 Could you put a link to your UCLA course slide ?   Thanks.

**Comment by michael-weinstein** [comment]
The image above is the slide I was speaking about.  It should tell you how to plug in FIGARO outputs into DADA2.  The course webpage (containing all the course material) can be found here: https://qcb.ucla.edu/collaboratory/workshops/w11-metagenomics-analysis/

Let me know if I can be of more assistance.

**Comment by akhst7** [comment]
@michael-weinstein 

So I run Figaro and a flowing is the comparison of Figaro output vs Dada2 default.   

This is done by a default Dada2's filter, truncLen = c(240, 160) and maxEE = c(2, 2)

```
	                      input filtered denoisedF denoisedR merged nonchim
256-001_S1_L001_R1_001.fastq  77939    57555     56752     56267  48465   42850
256-003_S2_L001_R1_001.fastq 170784   133036    131258    131379 112690  105121
256-004_S3_L001_R1_001.fastq  81179    60757     59837     59520  50291   46903
256-005_S4_L001_R1_001.fastq 159002   108564    106641    106150  88025   81196
256-006_S5_L001_R1_001.fastq 132691    97890     95201     95578  78693   69936
```
and the one from Fiagro filer, truncLen = c(192, 112) and maxEE = c(2, 2)

```
                             input filtered denoisedF denoisedR merged nonchim
256-001_S1_L001_R1_001.fastq  77939    69333     68580     67719  60412   42850
256-003_S2_L001_R1_001.fastq 170784   155970    154414    151439 136187  105121
256-004_S3_L001_R1_001.fastq  81179    71924     70890     68972  61264   46903
256-005_S4_L001_R1_001.fastq 159002   140903    139022    130654 110059   81196
256-006_S5_L001_R1_001.fastq 132691   113347    110770    110176  97164   69936
```
After further filtering of unwanted taxa in phyloseq by; ` filter_taxa(ps.r, function(x) mean(x) > 1e-5, TRUE)` and picked up more taxa with Fiagro

```
no Fiagro
> ntaxa(ps.fr)
[1] 2448

with Fargo
> ntaxa(ps.figaro.fr)
[1] 2996
```
Top 10 most abundant ASVs from Dads'2 default and Figaro respectively :

```
sort(taxa_sums(ps.fr), decreasing = T)[1:10]
      ASV1       ASV3       ASV2       ASV4       ASV5       ASV7       ASV6      ASV10       ASV9      ASV11 
0.32391848 0.20331078 0.19989125 0.17821804 0.13337284 0.11333948 0.10900848 0.08386164 0.08089006 0.07276069 
```

```
sort(taxa_sums(ps.figaro.fr), decreasing = T)[1:10]
      ASV1       ASV3       ASV2       ASV4       ASV5       ASV7       ASV6      ASV10       ASV9      ASV11 
0.32391848 0.20331078 0.19989125 0.17821804 0.13337284 0.11333948 0.10900848 0.08386164 0.08089006 0.07276069 
```

and bar plots;

Dada2's 
![Rplot](https://user-images.githubusercontent.com/3075799/117041719-2430f100-acd9-11eb-8e37-d2890099fea4.png)

Figaro

![Rplot01](https://user-images.githubusercontent.com/3075799/117041803-39a61b00-acd9-11eb-99be-8fd992bd0d1d.png)


There does not appear to be much difference in top ASVs but  the bottom ones are different.    Does this seem to be right ?   

Thanks.

**Comment by michael-weinstein** [comment]
That sounds exactly right.  FIGARO will generally get you more filtered reads if you're using  a somewhat stringent filter or higher quality reads if you've opted for a looser filter and more (lower quality) reads.  Generally you should not see the conclusions change much with FIGARO unless you had been making very poor selections for trimming parameters previously.  With more reads comes more power, and what you're probably seeing here is an improvement in the lower-abundance ASVs.  Much like other sampling measurements, when sample size goes up, power improves.  When power improves, it isn't usually the high abundance signals that see the most benefit (in terms of accuracy, confidence, or even just straight up detection) from the increased power.

**Comment by akhst7** [comment]
Thanks !!
