### ISSUE TITLE
Running from command line fails when /data doesn't exist

### ISSUE THREAD

**Issue by calpan** [Zymo-Research/figaro#7]
When run from the command line, the log file location is not specifiable as a parameter and defaults to /data/output even when the -o argument is provided.  If this location does not exist (or write permissions are not available), the program aborts immediately.

**Comment by michael-weinstein** [comment]
I have another branch currently being fixed to help with importation as a python package.  This is in the queue right after that one gets merged in.

**Comment by michael-weinstein** [comment]
(ETA of less than a week)

**Comment by michael-weinstein** [comment]
Sorry for the delay, trying to rush some other apps out quickly.  I just closed a different issue and this issue with either be next on my list or handled after one other quick bug fix.

**Comment by michael-weinstein** [comment]
Appears to be fixed with the latest release.
