### ISSUE TITLE
Cannot run from command line

### ISSUE THREAD

**Issue by jfq3** [Zymo-Research/figaro#9]
I am not able to run figaro. At first I got the message that figaroSupport could not be imported: 

(figaro) [quensenj@dev-intel16 figaro]$ python figaro.py -i ~/zchen_its2_test/raw_data/ -o ~/zchen_its2_test/figaro_out -a 450 -f 18 -r 20
Traceback (most recent call last):
  File "figaro.py", line 2, in <module>
    from . import figaroSupport
ImportError: cannot import name 'figaroSupport'

I changed the second line in figaro.py from:
from . import figaroSupport
to:
import figaroSupport

That seemed to solve the first problem, but then I got a permission denied error: 

(figaro) [quensenj@dev-intel16 figaro]$ python figaro.py -i ~/zchen_its2_test/raw_data/ -o ~/zchen_its2_test/figaro_out -a 450 -f 18 -r 20
<Logger __main__ (WARNING)>
Traceback (most recent call last):
  File "figaro.py", line 194, in <module>
    setLogging()
  File "figaro.py", line 122, in setLogging
    loggingParameters = getLoggingParameters()
  File "figaro.py", line 110, in getLoggingParameters
    os.makedirs(logFilePath)
  File "/mnt/home/quensenj/miniconda3/envs/figaro/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/mnt/home/quensenj/miniconda3/envs/figaro/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/data'

I have no idea where it is trying to write the log file. I would assume that if not in the output directory, then in the directory I am running from (~/figaro). I have write permissions to both.

**Comment by michael-weinstein** [comment]
Alright, I'll have a look at this.  The issue with the logging is a known problem and I'm working on a fix for it right now, but I'm slightly delayed due to being at the NIST microbiome conference.

**Comment by michael-weinstein** [comment]
Appears to be resolved in latest release.

**Comment by gailenriquez** [comment]
Hi I am trying to run https://github.com/Zymo-Research/miqScore16SPublic, and I get this error when I run the docker code to trim AttributeError: module 'Figaro' has no attribute 'figaroSupport'
